-- CREATE TABLE audits (
--       audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--       table_name       VARCHAR2(255),
--       transaction_name VARCHAR2(10),
--       by_user          VARCHAR2(30),
--       transaction_date DATE
-- );

create or replace trigger customer_audits
after update or DELETE
on emp_copy
for each row
declare 
    l_transaction varchar(20);

begin 
    if updating then
        l_transaction := 'update';
    elsif deleting then 
        l_transaction := 'delete';
    end if;

    insert into audits(table_name, transaction_name, by_user, transaction_date)
    values('emp_copy', l_transaction, user, sysdate);
end;